namespace: vaultwarden

helmCharts:
  - name: vaultwarden
    releaseName: vaultwarden
    namespace: vaultwarden
    repo: https://diademiemi.github.io/charts
    version: '0.3.0'
    valuesInline:
      image:
        repository: vaultwarden/server
        pullPolicy: IfNotPresent
        tag: 1.30.5

      env:
        SIGNUPS_ALLOWED: false
        INVITATIONS_ALLOWED: true
        DOMAIN: https://vault.plum.homelab
        SMTP_HOST: plum.homelab
        SMTP_FROM: no-reply@plum.homelab
        WEB_VAULT_ENABLED: true
        ADMIN_TOKEN: 'INITIAL_TOKEN_CHANGE_IN_UI'

      ingress:
        enabled: true

        hosts:
          - host: vault.plum.homelab
            paths:
              - path: /
                pathType: Prefix

        tls:
          - secretName: vault-plum-cert
            hosts:
              - vault.plum.homelab

      persistence:
        enabled: true
        accessMode: ReadWriteOnce
        size: 32000Mi
        mountPath: /data
        extraVolumes: []
