---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
  - name: cilium
    releaseName: cilium
    repo: https://helm.cilium.io/
    version: 1.18.4
    valuesFile: values.yaml

resources:
- pool.yaml
- l2-announcement.yaml
